from .storyboard_node import NODE_CLASS_MAPPINGS as SB_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SB_DISPLAY_NAME_MAPPINGS
from .prompt_extra_node import NODE_CLASS_MAPPINGS as PE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PE_DISPLAY_NAME_MAPPINGS

# รวม mappings จากทุกโมดูล
NODE_CLASS_MAPPINGS = {**SB_CLASS_MAPPINGS, **PE_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**SB_DISPLAY_NAME_MAPPINGS, **PE_CLASS_MAPPINGS if False else SB_DISPLAY_NAME_MAPPINGS}
